### ISSUE TITLE
select2 should show the "text" for selected options instead of the "value"

### ISSUE THREAD

**Issue by CitySim** [mpneuried/iggy#12]
![bildschirmfoto 2015-03-27 um 10 46 09](https://cloud.githubusercontent.com/assets/109395/6865499/8c4e4462-d46e-11e4-8ac9-651ce000a3b6.png)
![bildschirmfoto 2015-03-27 um 10 46 21](https://cloud.githubusercontent.com/assets/109395/6865501/8e6efeda-d46e-11e4-97a0-58e73ecf0b75.png)

**Comment by mpneuried** [comment]
Here's a example how to define a facet of type `select` with labels and Groups.
It was optimized in version `0.0.6`.

``` js
{
    type: "select",
    name: "multigroup",
    label: "Select Multi Group",
    multiple: true,
    options: [ 
        { value: "usa", label: "United States", group: "America" },
        { value: "can", label: "Canada", group: "America" },
        { value: "jp", label: "Japan", group: "Asia" },
        { value: "cn", label: "China", group: "Asia" },
        { value: "ger", label: "Germany", group: "Europe" }
    ]
}
```

**Comment by CitySim** [comment]
does not seem to work for us. perhaps because we use a dataAdapter and custom templates set by the adapter (`templateSelection`, `templateResult`). our facet looks like this:

``` javascript
{
    type: "select"
    label: "Salesmen"
    name: "salesmen"
    modify: modify
    multiple: true
    opts:
        dataAdapter: autofetchAdapter.contacts
        width: 300
}
```

tried to set `label` in the data returned from the adapter, but that doesn't change anything. still only the id

**Comment by mpneuried** [comment]
Will the `autofetchAdapter.contacts` work with a regular select2?
I will try to do a test with your usage type and give you a feedback or a solution.

**Comment by mpneuried** [comment]
Can you provide me an example of your select2 dataAdapter Solution?

**Comment by CitySim** [comment]
``` js

},{
    type: "select"
    label: "Colors Approved"
    name: "Colors Approved"
    fields: [ "_style/approvals/col" ]
    modify: approvalModify
    options: [
        { value: "true", label: "Approved" }
        { value: "false", label: "Not Approved" }
    ]
},{
```

![bildschirmfoto 2015-03-30 um 13 38 32](https://cloud.githubusercontent.com/assets/109395/6895590/2119939c-d6e2-11e4-82c3-a818a2db036d.png)

normal `options` also isn't working, not sure what is did wrong here
