### ISSUE TITLE
vertical scrolling in facet select dropdown

### ISSUE THREAD

**Issue by CitySim** [mpneuried/iggy#15]
![bildschirmfoto 2015-03-27 um 13 45 23](https://cloud.githubusercontent.com/assets/109395/6867976/98c19532-d487-11e4-869f-b126fa868869.png)

also happens on the example page

**Comment by mpneuried** [comment]
Please try to set the with via `opts.width`.

See https://select2.github.io/options.html#width

**E.g.:**

```
opts: {
    width: "resolve"
}
```

**Comment by CitySim** [comment]
checked again, it's the chrome beta version.
