### ISSUE TITLE
CSS ClassName

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#27]
Iggy $el
<div class="js-iggy">
Die CSS Classen werden ohne Leerschlag hinzugefügt.
Resultat --> <div class="js-iggyiggy clearfix">

D.h. man muss immer <div class="js-iggy "></div> <--- mit Leerschlag

**Comment by CitySim** [comment]
``` html
<!-- before -->
<div class="js-iggy"></div>
<!-- after -->
<div class="js-iggyiggy clearfix"></div>
<!-- should be -->
<div class="js-iggy iggy clearfix"></div>
```

**Comment by mpneuried** [comment]
fixed with version `0.0.17`.
83e8984d9dc6f90942f2ba55a424b70ed36da579

> FYI: Tests with the new Backbone version `1.2.x` are failing
