### ISSUE TITLE
Facet search also finds class name of class names

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#34]
Search for a facet with the name "la" -> see screenshot

![bildschirmfoto 2015-10-01 um 11 48 40](https://cloud.githubusercontent.com/assets/157063/10217819/923283fe-6832-11e5-8e9a-d48720d0cb23.png)

**Comment by mpneuried** [comment]
this one looks like a defect configuration.

Probably you tried a config like this:

``` js
// ...
,{
    type: "event",
    name: "run",
    label: "<i class='fa fa-search'></i> Suchen",
    event: "run",
    cssclass: "runsearch"
},
// ...
```

Can you provide me an example configuration?

**Comment by tcs-apeters** [comment]
It is like your example.

**Comment by mpneuried** [comment]
I added a option called `labeltemplate`.
E.g.:

``` js
{
        type: "string",
        name: "simple",
        label: "Simple",
        labeltemplate: "<i class='fa fa-quote-left'></i> <strong>{{label}}</strong> <i class='fa fa-quote-right'></i> ",
        options: [ "frist", "second", "last" ]
    }
```

The key `{{label}}` will replaced with real label.
So it's possible to design the selection label without changing the searchable label.
