### ISSUE TITLE
Most used facets by user should be displayed at the beginning/top

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#38]

**Comment by mpneuried** [comment]
How can i know the most used facets?

**Comment by mpneuried** [comment]
**Solution:**

a new sorting facet option will be added.

The first sorting criteria should be `sort` and if the `sort` is equal the facets will in alphabetic order. 
Every facet will have a default `sort = 0`. So if no `sort` is defined all facets will be in alphabetic order.

E.g:

```
{
    type: "string",
    name: "simple",
    label: "Simple",
    sort: 23
}
```

**Comment by mpneuried** [comment]
**Solution:**

Every Facet can have a attribute `sort` that is default `0`.
A higher sort will push the facet up the list `(+n) > 0 > (-n)`.
If the sort of 2 facets are equal they will be sorted in alphabetic order from `A > Z`.

It's possible to change the direction by setting the option `dir:"desc"`. The default `dir` is `asc`.

``` js
var facets = [ ... ];
var iggy = newIggy( facets, "#selector", { dir: "desc" } );
```

In this Case it will bi sorted `(-n) > 0 > (+n)` and if `sort` is equal by name  `Z > A`.
