### ISSUE TITLE
History of last search as option to reselect them

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#39]

**Comment by mpneuried** [comment]
A possible solution:
Iggy will get a method and/or event handle to set values. 
So you can add a `type: "event"` to trigger a set of values.
so you can hold the latest search(es) within your app and set them on the event of your custom button.

**Comment by mpneuried** [comment]
The solution will be implemented by the sorting feature #38.
Then it's possible to rate the most used facets higher than the others so they will be positioned at the top.
