### ISSUE TITLE
Type: Array Empty - Delete last value removes complete facet

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#53]
See attached image as reference

![bildschirmfoto 2016-03-17 um 09 13 55](https://cloud.githubusercontent.com/assets/157063/13840161/ed7a2948-ec20-11e5-8f0f-e9ae0a8986b5.png)

![bildschirmfoto 2016-03-17 um 09 14 02](https://cloud.githubusercontent.com/assets/157063/13840160/ed75cace-ec20-11e5-90c1-f4dbe2eae618.png)

**Comment by mpneuried** [comment]
Should a delete of the last element lead to the state to add new facets?

**Comment by mpneuried** [comment]
Another solution:
Make array elements editable via click. So a delete and a edit button over the element exists

**Comment by mpneuried** [comment]
i implemented the edit solution. Please let ne know if it matches your requirements

**Comment by tcs-apeters** [comment]
Edit and remove is not working for me. Both remove the  complete facet and not the value.

**Comment by mpneuried** [comment]
i tried it in FF, Chrome and Safri and it works.
Can you tell me the facet configuration, to be able to reproduce it?
