### ISSUE TITLE
Predefined open search Facets (string)

### ISSUE THREAD

**Issue by trietz** [mpneuried/iggy#61]
Predefined Iggy Facet: {"keywords":" "}

if($('.js-iggy-box_#Request.DSCMD.Element#').find('.sub-name-keywords li').html() == ' '){
			$('.js-iggy-box_#Request.DSCMD.Element#').find('.sub-name-keywords li').click();
			$('.js-iggy-box_#Request.DSCMD.Element#').find('.sub-name-keywords .subselect input').val('');
		}

**Comment by mpneuried** [comment]
new facet option `persistent`: This will deactivate the close button.
new facet option `active`: This will trigger a open of the facet.

**Comment by mpneuried** [comment]
FYI: renamed `presistend` to `pinned`

**Comment by trietz** [comment]
Active geht leider nicht bei Type String und pinned verhält sich auch nicht ganz korrekt.

Bitte einmal melden, dann kann ich Dir das besser Zeigen.

**Comment by mpneuried** [comment]
Hast Recht, `active` hatte ich noch nicht drin.
