### ISSUE TITLE
Facet Sorting changes after post...

### ISSUE THREAD

**Issue by trietz** [mpneuried/iggy#62]

**Comment by mpneuried** [comment]
The predefined facets should be displayed in the order o the given array

**Comment by mpneuried** [comment]
I coun't find an error inside iggy here.
Probably you're passing in the facets in a different order as you generated it before ...
Could you check this inside your implementation please!?

**Comment by trietz** [comment]
**So sieht das Formpost aus:**
dsiggy:"{"keywords":"+haring","contact_organisation.country_organisation":["Albania"]}"

**So sieht der Inhalt im Textarea aus nachdem Post aus:**
{"keywords":" haring","contact_organisation.country_organisation":["Albania"]}

**Das kommt als Attribute bei unsere Function dsiggy an:**
prefill : '{"keywords":" haring","contact_organisation.country_organisation":["Albania"]}',

**So rufen initialisieren wir Dein Iggy:**
this.iggy = new IGGY(@$el.find('.js-iggy'), facets, { modifyKey: "modified",dir: "asc", sortby: "label" })

Ich konnte keine Stelle bei uns im Code finden, die IGGY neu sortiert.

Vielleicht magst Du noch einmal schauen.

**Comment by trietz** [comment]
Habe nochmal mit Sven gesproche, er mein wir müssen Dir vielleicht noch das Such Array mit reingeben.

Bitte dazu noch einmal melden.

**Comment by mpneuried** [comment]
Ich bekomme das Facet array in der Reihe wie ich es anzeige.

![bildschirmfoto 2017-01-26 um 08 13 27](https://cloud.githubusercontent.com/assets/300631/22323019/21cdf0f4-e3a0-11e6-8324-1b4add5042b5.png)
> Ich habe die Daten direkt beim Aufruf von Iggy abgegriffen.
![bildschirmfoto 2017-01-26 um 08 22 47](https://cloud.githubusercontent.com/assets/300631/22323103/ad1553d2-e3a0-11e6-9f9c-c1799f2eefe9.png)


Somit müsst ihr die facets bei euch umsortieren bevor ihr mir diese rein gebt.
Iggy hat hier leider keine andere Möglichkeit, weil diese Liste die einzige Information ist die ich habe. Das optionale `sort` Feld bezieht sich ein auf die Ausgabe innerhalb der Auswahl.

**Comment by trietz** [comment]
Was können wir dir dazu noch zur Verfügung stellen, damit es so angezeigt
wird wie ausgewählt?

Am 26.01.2017 um 08:23 schrieb M. Peter <notifications@github.com>:

Ich bekomme das Facet array in der Reihe wie ich es anzeige.

[image: bildschirmfoto 2017-01-26 um 08 13 27]
<https://cloud.githubusercontent.com/assets/300631/22323019/21cdf0f4-e3a0-11e6-8324-1b4add5042b5.png>

Ich habe die Daten direkt beim Aufruf von Iggy abgegriffen.
[image: bildschirmfoto 2017-01-26 um 08 22 47]
<https://cloud.githubusercontent.com/assets/300631/22323103/ad1553d2-e3a0-11e6-9f9c-c1799f2eefe9.png>

Somit müsst ihr die facets bei euch umsortieren bevor ihr mir diese rein
gebt.
Iggy hat hier leider keine andere Möglichkeit, weil diese Liste die einzige
Information ist die ich habe. Das optionale sort Feld bezieht sich ein auf
die Ausgabe innerhalb der Auswahl.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/mpneuried/iggy/issues/62#issuecomment-275323258>, or mute
the thread

**Comment by mpneuried** [comment]
Ich könnt einfach die Reihenfolge der Facets ändern.

Ansonsten müsste ich noch ein zweites Sorting, neben dem für die Auswahl-Liste, einführen um die Reihenfolge der predefined/Pinned Facets zu sortieren. Das ist meiner Ansicht aber overkill ... Da steigt ja dann irgendwann keiner mehr durch.

**Comment by mpneuried** [comment]
@trietz Ist vermutlich nun geklärt, oder?

**Comment by trietz** [comment]
Ja lassen wir jetzt erstmal so, kann aber nochmal aufkommen ;)

Viele Grüße
Tim Rietz
*__________________________________________________________*

  Tim Rietz
  (Key Account Manager)

*  Team Centric Software GmbH & Co. KG*
  Averhoffstraße 17
  D-22085 Hamburg
  Tel: +49-40-303 9278-10
  Fax: +49-40-303 9278-28
  Email: tr@tcs.de
  Websites:
  www.tcs.de
  www.fleetplan.net
  www.dynasite.de
  www.webmart.de
  USt-IdNr: DE194938637
  Steuernummer: 43/662/01721
  Handelsregister / Register of Companies:
  HRA 107331 / Hansestadt Hamburg
  Geschäftsführer / Managing Directors:
  Patrick Liess, Robert Liess
  Komplementärin:
  Team Centric Software Verwaltungs GmbH
  HRB 103067 / Hansestadt Hamburg


*_________________________________________________________*
Der Inhalt dieser E-Mail ist vertraulich und ausschließlich für den
Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat sein sollten,
bitten wir Sie, den Absender zu informieren und diese E-Mail zu löschen.
Auch wenn wir alle verkehrsüblichen Maßnahmen unternommen haben, um das
Risiko der Verbreitung virenbefallener Software oder E-Mails zu minimieren,
schließen wir die Haftung für jeglichen Verlust oder Schaden aus, der durch
Software-Viren verursacht wird. Wir erstellen unsere E-Mails sorgfältig,
dennoch kann diese E-Mail verändert oder verfälscht worden sein. Wir
schließen daher die rechtliche Verbindlichkeit der E-Mail aus und
übernehmen keine Haftung oder Gewähr für die fehlerfreie Übermittlung.

The information contained in this e-mail is confidential. It is intended
solely for the addressee. If you are not the intended recipient, please
notify the sender immediately and delete this e mail from your system. We
have taken precautions to minimize the risk of transmitting software
viruses but we do not accept any liability for loss or damage caused by
such viruses. Although we send our e-mails carefully, this e-mail may have
been altered or falsified. Therefore, the content of this e-mail is not
legally binding and we do not accept any legal liability or responsibility
for correct transmission.
