### ISSUE TITLE
Tab Probleme

### ISSUE THREAD

**Issue by trietz** [mpneuried/iggy#68]
Leider konnt ich IGGY so nicht mit ins Update nehmen, da Du den Tab für alle Masken deaktivierst.

Wir haben auch noch Probleme mit dem Click auf den Search Button.

Bitte melde Dich einmal am Montag, müssten das leider dringend fixen.

**Comment by mpneuried** [comment]
Das Problem mit dem Tab ist klar.
Mit "Probleme mit dem Search Button" kann ich leider nichts anfangen.

**Comment by trietz** [comment]
Das muss ich Dir Zeigen, das Verhalten ist etwas nervös..schwer zu
beschreiben.

Viele Grüße
Tim Rietz
*__________________________________________________________*

  Tim Rietz
  (Key Account Manager)

*  Team Centric Software GmbH & Co. KG*
  Averhoffstraße 17
  D-22085 Hamburg
  Tel: +49-40-303 9278-10
  Fax: +49-40-303 9278-28
  Email: tr@tcs.de
  Websites:
  www.tcs.de
  www.fleetplan.net
  www.dynasite.de
  www.webmart.de
  USt-IdNr: DE194938637
  Steuernummer: 43/662/01721
  Handelsregister / Register of Companies:
  HRA 107331 / Hansestadt Hamburg
  Geschäftsführer / Managing Directors:
  Patrick Liess, Robert Liess
  Komplementärin:
  Team Centric Software Verwaltungs GmbH
  HRB 103067 / Hansestadt Hamburg


*_________________________________________________________*
Der Inhalt dieser E-Mail ist vertraulich und ausschließlich für den
Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat sein sollten,
bitten wir Sie, den Absender zu informieren und diese E-Mail zu löschen.
Auch wenn wir alle verkehrsüblichen Maßnahmen unternommen haben, um das
Risiko der Verbreitung virenbefallener Software oder E-Mails zu minimieren,
schließen wir die Haftung für jeglichen Verlust oder Schaden aus, der durch
Software-Viren verursacht wird. Wir erstellen unsere E-Mails sorgfältig,
dennoch kann diese E-Mail verändert oder verfälscht worden sein. Wir
schließen daher die rechtliche Verbindlichkeit der E-Mail aus und
übernehmen keine Haftung oder Gewähr für die fehlerfreie Übermittlung.

The information contained in this e-mail is confidential. It is intended
solely for the addressee. If you are not the intended recipient, please
notify the sender immediately and delete this e mail from your system. We
have taken precautions to minimize the risk of transmitting software
viruses but we do not accept any liability for loss or damage caused by
such viruses. Although we send our e-mails carefully, this e-mail may have
been altered or falsified. Therefore, the content of this e-mail is not
legally binding and we do not accept any legal liability or responsibility
for correct transmission.

**Comment by mpneuried** [comment]
ich hab mal nach besten Wissen und Gewissen etwas korrigiert
https://github.com/mpneuried/iggy/releases/tag/0.2.4
