### ISSUE TITLE
Blur Probleme

### ISSUE THREAD

**Issue by trietz** [mpneuried/iggy#69]
Nervöses Blur Verhalten beim verlassen von offenen Iggy Facets.

Zu sehen beim Addressbook, beim initial Öffnen und dann direkt einen Kontakt auswählen.

Für Fragen stehe ich Dir gerne zur Verfügung.

**Comment by mpneuried** [comment]
![bildschirmfoto 2017-01-31 um 06 15 37](https://cloud.githubusercontent.com/assets/300631/22453124/b6ad7048-e77c-11e6-9a53-0a0572e3abf0.png)
Ich kann es mir leider nicht ansehen ...

**Comment by mpneuried** [comment]
Bei mir kann bei mir lokal keine Probleme feststellen
