### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by fabien** [mpneuried/iggy#70]
The example code at http://mpneuried.github.io/iggy/ seems to be broken.

**Comment by mpneuried** [comment]
Thanks for the info.
After the large amount of changes and versions, during the last weeks, the example has been somewhat neglected ;-)
Until there is a little bit time i will fix it

**Comment by mpneuried** [comment]
The example is fixed and a added more detailed docs ;-)

**Comment by fabien** [comment]
@mpneuried thanks! I was wondering how the fix only appears in `/dist` and not anywhere else in this commit (`_src` for example).

**Comment by mpneuried** [comment]
Ah yes, sorry, it was a little mess, because of the gh-pages caching ;-)
The relevant fix is here https://github.com/mpneuried/iggy/commit/4b7e783fb35129a696be3948a94cf572f035398e#diff-d66a2e4e815b7e4f5a1b42aa6d44e5eb
