### ISSUE TITLE
transparent background in array facet with really long text

### ISSUE THREAD

**Issue by CitySim** [mpneuried/iggy#72]
![bildschirmfoto 2017-07-17 um 16 01 09](https://user-images.githubusercontent.com/109395/28271606-467eb94c-6b09-11e7-91a8-0cd20168fd25.png)

![bildschirmfoto_2017-06-08_um_14 04 19](https://user-images.githubusercontent.com/109395/28271670-7c6eb91c-6b09-11e7-963f-1c0131b1dd0e.png)

**Comment by mpneuried** [comment]
Every element is scrollable if too long
