### ISSUE TITLE
Position of Search and Add facet button

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#73]
We would like to have both buttons left aligned.
See image as reference.

![bildschirmfoto 2017-10-10 um 11 17 53](https://user-images.githubusercontent.com/157063/31378870-e3cd07cc-adac-11e7-936c-d398e2509508.png)

**Comment by mpneuried** [comment]
should this be implemented as an option?

**Comment by tcs-apeters** [comment]
Yes, I guess it is better to implement an option.
