### ISSUE TITLE
<i> Tag missing - fontawesome 5

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#74]
Pls add separated <i> tag for fa classes. Currently fa is applied to button tags. That does not work with with fontawesome 5. See screenshot.

![bildschirmfoto 2017-10-16 um 14 12 31](https://user-images.githubusercontent.com/157063/31611462-74bc1970-b27c-11e7-8168-e5cbb3dbc33b.png)

**Comment by mpneuried** [comment]
So every element with the class `fa` should have an additional call like `fa-narf`?

**Comment by mpneuried** [comment]
every font-awesome element should be a seperate html element. Best case an `<i>`
