### ISSUE TITLE
Select mit scrollbar

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#75]
1. Trying to scroll to right, is selecting the entry. Can't we just increase the width?
2. Removing selected facet is not working

![bildschirmfoto 2017-10-24 um 08 56 41](https://user-images.githubusercontent.com/157063/31928684-582be024-b899-11e7-95d4-033017c001a7.png)

**Comment by mpneuried** [comment]
Increasing the with will not solve the Problem it will only reduce the number cases when it happens.
There has to be a max-width for the selects.

so wrapping the texts could be a solution:
![bildschirmfoto 2017-10-26 um 09 41 48](https://user-images.githubusercontent.com/300631/32040718-04968974-ba32-11e7-8af9-adfe48256802.png)
